name: Build Flet Android APK

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: 'pip' # Otimiza o tempo de build cacheando os downloads do pip

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libgfortran5

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flet
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.41.7"

      - name: Build APK
        env:
          CI: "true"
          FLET_CI: "1"
          FLET_NON_INTERACTIVE: "true"
          FLET_ANALYTICS_OPTOUT: "1"
        run: |
          # O Flet precisa ler o flet.yaml e o requirements.txt na raiz do projeto
          flet build apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: paulstretch-apk
          path: build/apk/*.apk
